server:
  port: 8765

spring:
  zipkin:
    base-url: http://localhost:9411
  #数据源
  datasource:
       url: jdbc:mysql://127.0.0.1:3306/emp-sys?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
       username: root
       password: root
       driver-class-name: com.mysql.jdbc.Driver

#mybatis
#mybatis:
    #mapper-locations: classpath:mappers/*.xml
    #type-aliases-package: com.weirdo.report.pojo

queue: mytest

mqtt_url: tcp://10.2.100.45:1883
mqtt_clientId: weirdo-cliendId
#amq过期时间,防止积压(秒)
mqtt_expiration: 20

activemq:
  broker-url: tcp://10.2.100.45:61616
  user: admin
  password: admin


#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    auto-runtime-dialect: true

#文件模版名
fileName: 模版.xlsx
filePath: template/模版.xlsx

#日志
logging:
  #file: C:\\logs\\emp-sys\\plan-service.log(windows)
  #file: /Users/weirdo/logs/emp-sys/plan-service.log(mac)
  file: /Users/weirdo/logs/emp-sys/report-service.log
  level:
    root: info



