server:
  port: 8764

spring:
  zipkin:
    base-url: http://localhost:9411

  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    encoding: UTF-8
    mode: HTML5
    suffix: .html
  mvc:
    static-path-pattern: /static/**

